=== jhonsnowsec/web3-security-toolkit/bounty-pocs/fassets/deployment/config/core-vault-manager-parameters.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "description": "JSON schema url",
            "type": "string"
        },
        "assetManager": {
            "description": "The corrsponding asset manager, either the address or the name in the contracts file.",
            "type": "string"
        },
        "chainPaymentFee": {
            "description": "The fee charged by the chain for each payment, in chain base units.",
            "pattern": "^[0-9 ]+$",
            "type": "string"
        },
        "custodianAddress": {
            "description": "The underlying address of the core vault custodian.",
            "pattern": "^\\w+$",
            "type": "string"
        },
        "escrowAmount": {
            "description": "Single escrow amount, in chain base units (setting to 0 disables escrows).",
            "pattern": "^[0-9 ]+$",
            "type": "string"
        },
        "escrowEndTimeSeconds": {
            "description": "The time of day (UTC) when the escrows expire. Exactly one escrow per day will expire.",
            "type": "integer"
        },
        "initialSequenceNumber": {
            "description": "The nonce (sequence number) on the multisig address at the deploy time.\nAfter deploy, only transactions requested by the core vault manager should be sent from this address, otherwise the nsequence numbering will lose sync.",
            "pattern": "^\\w+$",
            "type": "integer"
        },
        "minimalAmountLeft": {
            "description": "The minimal amount that will be left on the multisig after escrowing, in chain base units.",
            "pattern": "^[0-9 ]+$",
            "type": "string"
        },
        "underlyingAddress": {
            "description": "The underlying address of the core vault multisig.",
            "pattern": "^\\w+$",
            "type": "string"
        }
    },
    "required": [
        "assetManager",
        "chainPaymentFee",
        "custodianAddress",
        "escrowAmount",
        "escrowEndTimeSeconds",
        "initialSequenceNumber",
        "minimalAmountLeft",
        "underlyingAddress"
    ],
    "type": "object"
}

=== jhonsnowsec/web3-security-toolkit/bounty-pocs/fassets/deployment/config/coston2/core-vault-manager-testxrp.json
{
    "$schema": "../core-vault-manager-parameters.schema.json",
    "assetManager": "AssetManager_FTestXRP",
    "underlyingAddress": "rDhpmiPq4BVBDWMVdSrmkgt8thKyRzGV1p",
    "initialSequenceNumber": 10167328,
    "custodianAddress": "r3GhxcaM4f9BJXEu1JLRgDXZpHJw6ugkH4",
    "escrowAmount": "10000 000000",
    "escrowEndTimeSeconds": 46800,
    "minimalAmountLeft": "15000 000000",
    "chainPaymentFee": "400"
}

=== jhonsnowsec/web3-security-toolkit/bounty-pocs/fassets/deployment/config/coston/core-vault-manager-testxrp.json
{
    "$schema": "../core-vault-manager-parameters.schema.json",
    "assetManager": "AssetManager_FTestXRP",
    "underlyingAddress": "rLKM1Sr8CMThK18AxtbDo4r4y59pYq8Xzo",
    "initialSequenceNumber": 5757519,
    "custodianAddress": "rBRtxBnAjKKzKYkks493N2yW4Vr28yfYdz",
    "escrowAmount": "10000 000000",
    "escrowEndTimeSeconds": 43200,
    "minimalAmountLeft": "10000 000000",
    "chainPaymentFee": "100"
}

=== jhonsnowsec/web3-security-toolkit/bounty-pocs/fassets/deployment/config/songbird/core-vault-manager-xrp.json
{
    "$schema": "../core-vault-manager-parameters.schema.json",
    "assetManager": "AssetManager_FXRP",
    "underlyingAddress": "rpWpGbeMQSQLhitEHVtfTrArByj3xh5Rt1",
    "initialSequenceNumber": 95855925,
    "custodianAddress": "rDvuj6yYU6sT1waeaqW2f2pVQkvDUaDKrg",
    "escrowAmount": "150 000 000000",
    "escrowEndTimeSeconds": 50400,
    "minimalAmountLeft": "150 000 000000",
    "chainPaymentFee": "400"
}

=== jhonsnowsec/web3-security-toolkit/bounty-pocs/fassets/deployment/config/hardhat/core-vault-manager-xrp.json
{
    "$schema": "../core-vault-manager-parameters.schema.json",
    "assetManager": "AssetManager_FXRP",
    "underlyingAddress": "rUqtdsu9qALN2pxeX8zJ3pokUKW66wFZoT",
    "initialSequenceNumber": 0,
    "custodianAddress": "raaRxtgcdPNK2M4ENKiukG5TawrMwxwn68",
    "escrowAmount": "1000 000000",
    "escrowEndTimeSeconds": 43200,
    "minimalAmountLeft": "1000 000000",
    "chainPaymentFee": "100"
}
